### ISSUE TITLE
Database Schema Review

### ISSUE THREAD

**Issue by BCrawfordScott** [breizeway/get-some-eggs-while-youre-at-it#1]
Great work, team!  This looks really solid.

- [x] Add createdAt and updatedAt to all tables
- Suggestion: the time intervals and repetitions on the task table are really cool, but they can be a difficult feature to implement.  I would suggest leaving them off and adding them as a bonus later. that gives you the time and energy to focus on the core functionality of your project.

Keep up the good work!

**Comment by jaikens19** [comment]
Completed DB schema with updates: https://drawsql.app/n-a-41/diagrams/remember-the-milk#
